# ================ 开关控制模块 ================
enable:
  # 路由板块开关
  router:
    comments: true # 是否启用留言板路由
    gossip: true # 是否启用闲言碎语路由
    friendLinks: true # 是否启用友链路由

  # 主页模块开关
  home:
    avatar: true # 是否显示头像
    motto: true # 是否显示座右铭
    hitokoto: true # 是否显示一言
    tags: true # 是否显示标签云
    dateTime: true # 是否显示时钟
    welcome: true # 是否显示欢迎语
    social: true # 是否显示社交链接
    githubContribution: true # 是否显示GitHub贡献图
    siteNavs: true # 是否显示网站导航
    projects: true # 是否显示项目展示
    skills: true # 是否显示技术栈

  # 留言板模块开关
  comments:
    banner: true # 是否显示横幅
    bannerText: true # 是否显示横幅文本

  # 友链模块开关
  friendLinks:
    description: true # 是否显示友链简介

# ================ 个人信息配置 ================
name: "曦暮流年" # 显示在页面的昵称（必填）

avatar: "img/avatar.png" # 头像路径（存放在/public/img/目录下）
description: "懒惰往往是创新的催化剂" # 简短的个人介绍（建议20字内）

# 头像状态标签
avatar_status:
  icon: "✨" # 状态图标（使用Windows徽标键+>打开emoji选择器）
  text: "学习中~" # 状态文字（建议3-4个汉字）

# ================ 座右铭配置 ================
motto:
  top: "能躺着绝不坐着," # 座右铭上半句
  bottom: "能坐着绝不站着." # 座右铭下半句

# ================ 个人标签 ================
tags:
  - "前端"
  - "后端"
  - "随遇而安"
  - "IT"
  - "懒癌患者"
  - "菜鸡"
  - "修猫"
  - "修狗"
  - "Steam"
  - "农药"
  - "音乐迷"
  - "我的世界"
  - "吃麻麻香"
  - "打洲"

# ================ 背景图片 ================
background_image:
  - "/img/background/1.png"
  - "/img/background/2.png"
  - "/img/background/3.png"
  - "/img/background/4.png"
  - "/img/background/5.png"
  - "/img/background/6.png"

# ================ 社交链接 ================
social:
  - name: "GitHub"
    icon: "icon-GitHub"
    url: "https://github.com/ximuliunian"

  - name: "Gitee"
    icon: "icon-gitee"
    url: "https://gitee.com/ximuliunian"

  - name: "邮箱"
    icon: "icon-youxiang"
    url: "mailto:xmln@ximuliunian.top"

  - name: "QQ"
    icon: "icon-qq"
    url: "tencent://Message/?Uin=2515550574&websiteName=local.edu.com:8888=&Menu=yes"

  - name: "BiliBili"
    icon: "icon-bzhan"
    url: "https://space.bilibili.com/1304924540"

# ================ 站内导航 ================
siteNavs:
  - name: "博客"
    url: "https://blog.ximuliunian.top"
    icon: "icon-blog"

  - name: "笔记"
    url: "https://notes.ximuliunian.top"
    icon: "icon-notes"

  - name: "网页导航"
    url: "https://nav.ximuliunian.top"
    icon: "icon-nav"

  - name: "下载加速"
    url: "https://xzjs.ximuliunian.top"
    icon: "icon-xiazaijiasu"

  - name: "GPT"
    url: "https://gpt.ximuliunian.top"
    icon: "icon-gpt"

  - name: "云盘资源"
    url: "https://cloud-folder.ximuliunian.top/"
    icon: "icon-yunpan"

# ================ 项目展示 ================
projects:
  - name: "X-Home"
    icon: "icon-jiangbing"
    url: "https://github.com/ximuliunian/x-home"
    description: "本站同款个人主页"

  - name: "CloudExplorer"
    icon: "icon-zhuangshi"
    url: "https://github.com/ximuliunian/CloudExplorer"
    description: "本站同款云盘资源页面"

# ================ 技术栈图标 ================
skills:
  theme: "light" # 主题风格：light（亮色）/dark（暗色）
  list:
    - "idea"
    - "git"
    - "maven"
    - "java"
    - "spring"
    - "windows"
    - "python"
    - "vue"
    - "vite"
    - "vscode"
    - "mysql"
    - "redis"
    - "html"
    - "ubuntu"
    - "css"
    - "linux"
    - "js"
    - "github"
    - "docker"
    - "nodejs"
    - "nginx"
    - "markdown"
    - "githubactions"
    - "vim"
    - "cloudflare"
    - "kafka"
    - "rabbitmq"
    - "elasticsearch"
    - "ts"

# ================ ICP备案 ================
icp:
  - domain: "xmln.top"
    info: "豫ICP备2024053500号"

# ================ 评论系统 ================
giscus:
  repo: "ximuliunian/blog" # GitHub仓库（格式：owner/repo）
  repoId: "R_kgDOGuKRyg" # 仓库ID（在Giscus设置获取）
  category: "Announcements" # 如：Comments
  categoryId: "DIC_kwDOGuKRys4CVf53" # 分类ID
  theme: "light_protanopia" # 主题风格

# ================ 留言板配置 ================
_comment:
  cover: "/img/reviewCover.png" # 封面图路径
  title: "留言板" # 如：访客留言
  description: "少年，江湖之路漫长且未知，今朝有幸相逢，便是缘定一线。何不借此际会，留下一语豪言，以铭此情此景？" # 显示在顶部的描述文字

# ================ 友链高级配置 ================
_friendLinks:
  description:
    - "p:在网上冲浪时，总能遇到一些写得超棒的博客，里面的文章质量高得让人佩服"
    - "p:为了不和这么优秀的文章作者失之交臂，得赶紧和他们交换友情链接！这样不仅能分享好内容，还能结交志同道合的朋友，一起交流心得、共同成长"
    - "img:/img/friendLinks1.png"
    - "img:/img/friendLinks2.gif"

  scheme: # 本站信息（供他人申请友链时参考）
    name: "曦暮流年" # 名称
    url: "https://www.ximuliunian.top" # 链接
    avatar: "https://www.ximuliunian.top/img/avatar.png" # 头像
    desc: "懒惰往往是创新的催化剂" # 简介
    bgColor: "#8bfdd4" # 背景颜色

  require: # 友链申请要求
    - "ol:贵站已经添加的本站的链接"
    - "ol:贵站在中国大陆能够正常访问"
    - "ol:贵站符合中国大陆法律"
    - "p:如果符合要求的话可以根据上面表格的格式进行申请友链，比如："
    - "p:名称：xxx"
    - "p:简介：xxxxxxxxxx"
    - "p:填写完成之后在下方进行留言，至于本站信息就在上面表格之中"

  links: # 友链分类（按需添加）
    # 示例：
    # - sort: "技术博客"
    #   icon: "icon-zhineng"
    # - sort: "创意设计"
    #   icon: "icon-zhineng"

# ================ 闲言碎语配置 ================
_gossip:
  settings:
    public: 0 # 0=任何人都可以拉取我的内容/1=只有我关联的人可以拉取我的内容
    internalDisplay: 0 # 0=可以展示所有人的内容/1=只能展示关联我的人的内容

  links: # 关联站点（需完整URL）
    # 示例：
    # - "https://friend-site.com"
    # - "https://another-site.net"
